Repository jilleJr/TellMe, pull requests merged in 2022-02, with the labels that each got.

#10 Created 7 segment display
  .vscode/settings.json
  Assets/Prefabs/SegmentDisplay.meta
  Assets/Prefabs/SegmentDisplay/Digit.prefab
  Assets/Prefabs/SegmentDisplay/Digit.prefab.meta
  Assets/Prefabs/SegmentDisplay/Display.prefab
  Assets/Prefabs/SegmentDisplay/Display.prefab.meta
  Assets/Scenes/TestSegmentDisplayScene.unity
  Assets/Scenes/TestSegmentDisplayScene.unity.meta
  Assets/Scripts/SegmentDisplay.meta
  Assets/Scripts/SegmentDisplay/SegmentDigit.cs
  Assets/Scripts/SegmentDisplay/SegmentDigit.cs.meta
  Assets/Scripts/SegmentDisplay/SegmentDisplay.cs
  Assets/Scripts/SegmentDisplay/SegmentDisplay.cs.meta
  Assets/Scripts/SegmentDisplay/TestSegmentDisplayDriver.cs
  Assets/Scripts/SegmentDisplay/TestSegmentDisplayDriver.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#16 Easy copy join code
  Assets/JoinCodeScript.cs
  Assets/JoinCodeScript.cs.meta
  Assets/Scenes/HostOrJoinScene.unity
  Assets/Scripts/HostOrJoinScene/HostGameScript.cs
Labels: enhancement

#17 Join game
  Assets/Prefabs/HostOrJoinScene/Big validated field Variant.prefab
  Assets/Prefabs/HostOrJoinScene/Big validated field Variant.prefab.meta
  Assets/Prefabs/Steps status.prefab
  Assets/Scenes/HostOrJoinScene.unity
  Assets/Scripts/HostOrJoinScene/JoinGameScript.cs
  Assets/Scripts/HostOrJoinScene/JoinGameScript.cs.meta
  Assets/StreamingAssets.meta
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, area/coding

#12 Added score display model first draft
  Assets/Models.meta
  Assets/Models/ScoreDisplay.meta
  Assets/Models/ScoreDisplay/gen-uv-grid.png
  Assets/Models/ScoreDisplay/gen-uv-grid.png.meta
  Assets/Models/ScoreDisplay/score_display.fbx
  Assets/Models/ScoreDisplay/score_display.fbx.meta
Labels: enhancement

#21 Upgraded to Unity 2022.1.0b8
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: chore, area/coding

#20 Game scene mockup
  Assets/Animations.meta
  Assets/Animations/GameScene camera demo AC.controller
  Assets/Animations/GameScene camera demo AC.controller.meta
  Assets/Animations/GameScene camera demo animation.anim
  Assets/Animations/GameScene camera demo animation.anim.meta
  Assets/Materials.meta
  Assets/Materials/Contestants plattform floor.mat
  Assets/Materials/Contestants plattform floor.mat.meta
  Assets/Materials/Inner floor.mat
  Assets/Materials/Inner floor.mat.meta
  Assets/Materials/Outer floor.mat
  Assets/Materials/Outer floor.mat.meta
  Assets/Materials/Player score background.mat
  Assets/Materials/Player score background.mat.meta
  Assets/Materials/Question screen border.mat
  Assets/Materials/Question screen border.mat.meta
  Assets/Materials/Question screen inner.mat
  Assets/Materials/Question screen inner.mat.meta
  Assets/Materials/SegmentDisplayDigit.mat
  Assets/Materials/SegmentDisplayDigit.mat.meta
  Assets/PostProcessingProfile.asset
  Assets/PostProcessingProfile.asset.meta
  Assets/Prefabs/GameScene.meta
  Assets/Prefabs/GameScene/Audience person.prefab
  Assets/Prefabs/GameScene/Audience person.prefab.meta
  Assets/Prefabs/GameScene/Contestant.prefab
  Assets/Prefabs/GameScene/Contestant.prefab.meta
  Assets/Prefabs/SegmentDisplay/Digit.prefab
  Assets/Prefabs/SegmentDisplay/Display.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scenes/GameScene.unity.meta
  Assets/Scripts/GameScene.meta
  Assets/Scripts/GameScene/AudienceJumpingScript.cs
  Assets/Scripts/GameScene/AudienceJumpingScript.cs.meta
  Assets/Scripts/SegmentDisplay/SegmentDisplay.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, area/graphical

#19 Feature/host player list
  Assets/Prefabs/LobbyScene.meta
  Assets/Prefabs/LobbyScene/Player list.prefab
  Assets/Prefabs/LobbyScene/Player list.prefab.meta
  Assets/Prefabs/LobbyScene/PlayerListEntry.prefab
  Assets/Prefabs/LobbyScene/PlayerListEntry.prefab.meta
  Assets/Prefabs/LobbyScene/PlayerManager.prefab
  Assets/Prefabs/LobbyScene/PlayerManager.prefab.meta
  Assets/Scenes/HostOrJoinScene.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/LobbyScene.unity.meta
  Assets/Scenes/LoginScene.unity
  Assets/Scripts/HostOrJoinScene/HostGameScript.cs
  Assets/Scripts/HostOrJoinScene/JoinGameScript.cs
  Assets/Scripts/LobbyScene.meta
  Assets/Scripts/LobbyScene/JoinCodeScript.cs
  Assets/Scripts/LobbyScene/JoinCodeScript.cs.meta
  Assets/Scripts/LobbyScene/JoinCodeSetter.cs
  Assets/Scripts/LobbyScene/JoinCodeSetter.cs.meta
  Assets/Scripts/LobbyScene/LobbyScript.cs
  Assets/Scripts/LobbyScene/LobbyScript.cs.meta
  Assets/Scripts/LobbyScene/Player.cs
  Assets/Scripts/LobbyScene/Player.cs.meta
  Assets/Scripts/LobbyScene/PlayerList.cs
  Assets/Scripts/LobbyScene/PlayerList.cs.meta
  Assets/Scripts/LobbyScene/PlayerManager.cs
  Assets/Scripts/LobbyScene/PlayerManager.cs.meta
  Assets/Scripts/NetworkSessionData.cs
  Assets/Scripts/NetworkSessionData.cs.meta
  ProjectSettings/BurstAotSettings_StandaloneLinux64.json
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, area/coding

#24 Upgraded to Unity 2022.1.0b9
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: chore, area/coding
